###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "userName" : "Mike",
  "password" : "123456",
  "confirmPassword" : "123456",
  "gender" : "male"
}

###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "userName" : "Jane",
  "password" : "1234567",
  "confirmPassword" : "1234567",
  "gender" : "female"
}

###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "userName" : "Bob",
  "password" : "123456",
  "confirmPassword" : "123456",
  "gender" : "male"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "userName" : "Bob",
  "password" : "123456"
}

###
POST http://localhost:5000/api/auth/logout

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "userName" : "Mike",
  "password" : "123456"
}

###
POST http://localhost:5000/api/messages/send/6970bfab00ff7a284d8c703b
Content-Type: application/json

{
  "message" : "Mikeとしてログインして、Janeにメッセージを送信。"
}
